name: Encrypt and Deploy

on:
  push:
    branches: [main]

jobs:
  encrypt-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.11-nodejs20-slim
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Create token file
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
          OFFICER_PW: ${{ secrets.OFFICER_PASSWORD }}
        run: |
          echo "var API_TOKEN='***';" > token.js
          echo "var OFFICER_PASSWORD='***';" >> token.js
      - name: Install staticrypt
        run: npm install -g staticrypt@3.*
      - name: Remove template salt (if necessary)
        run: |
          if [ -f .staticrypt.json ]; then
            current_salt="$(grep -oP '(?<="salt": ")[^"]*' .staticrypt.json)"
            if [ "$current_salt" = "9fdd6a30e734b0ce7de31a0a221786bf" ]; then
              echo "Removed default salt to regenerate"
              rm .staticrypt.json
            fi
          fi
      - name: Embed assets
        run: |
          pip install beautifulsoup4
          python embed.py
      - name: Encrypt index
        run: >
          staticrypt index.html -p ${{ secrets.DECRYPTION_PASSPHRASE }} --short
          --template "password_template.html"
          --template-title "ELC Project Management"
          --template-instructions "Enter team password to continue"
          --template-button "Unlock"
          --template-color-primary "#CC9700"
          --template-color-secondary "#000000"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./encrypted
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
