name: Encrypt and Deploy

on:
  push:
    branches: [main]

jobs:
  encrypt:
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.11-nodejs20-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Git
        run: |
          apt-get clean && apt-get update -y
          apt-get install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install staticrypt
        run: npm install -g staticrypt@3.*
      - name: Remove template salt (if necessary)
        run: |
          if [ -f .staticrypt.json ]; then
            current_salt="$(grep -oP '(?<="salt": ")[^"]*' .staticrypt.json)"
            if [ "$current_salt" = "9fdd6a30e734b0ce7de31a0a221786bf" ]; then
              echo "Removed default salt to regenerate"
              rm .staticrypt.json
            fi
          fi
      - name: Embed assets
        run: |
          pip install beautifulsoup4
          python embed.py
      - name: Encrypt index
        run: >
          staticrypt index.html -p ${{ secrets.DECRYPTION_PASSPHRASE }} --short
          --template "password_template.html"
          --template-title "ELC Project Management"
          --template-instructions "Enter team password to continue"
          --template-button "Unlock"
          --template-color-primary "#CC9700"
          --template-color-secondary "#000000"
      - name: Push encrypted page to gh-pages
        run: |
          mv encrypted/index.html /tmp/index.html
          rm -rf encrypted
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          find . -not -path './.git/*' -not -name '.git' -delete
          mv /tmp/index.html .
          git add index.html
          git commit -m "encrypted page"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages --force
